sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: JimWL Blog
name: JimWL
description: 走自己的路，让别人说去吧
url: https://jJimWL.github.io
copyright_time: 2021
avatar: https://jimmy090703.github.io/assets/img/avatar.png
favicon: https://jimmy090703.github.io/assets/img/favicon.ico

github: https://github.com/JimWL
email: mailto:jimmyzhangshuning@outlook.com
rss: true

site_statistics: true
baidu_id: 7b9842791b53e908a29a8cd1078d694a

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
