sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/img"
    values:
      image: true

title: jimmy090703's page
name: jimmy090703
description: 欢喜编程的小学生~(￣▽￣)~*
url: https://jimmy090703.github.io
copyright_time: 2020
avatar: https://jimmy090703.github.io/assets/img/avatar.png
favicon: https://jimmy090703.github.io/assets/img/favicon.ico

github: https://github.com/jimmy090703
email: mailto:jimmyzhangshuning@outlook.com
rss: true

plugins:
  - rouge
  - kramdown
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji

exclude:
  - script
  - docs
  - vendor
  - Gemfile
  - Gemfile.lock
